### ISSUE TITLE
probe-rs For RISC-V esp chips

### ISSUE THREAD

**Issue by georgik** [esp-rs/esp-rs-backlog#1]
Adding flash algorithms for the esp32c3 etc. probe-rs uses [arm cmsis flash pack](https://arm-software.github.io/CMSIS_5/Pack/html/flashAlgorithm.html) to create flash algorithms. I started https://github.com/MabezDev/esp-flash-loader but it may just be better to write it in C, and re use the `esp_spi_flash` component of the IDF.

**Comment by MabezDev** [comment]
Closed via https://github.com/probe-rs/probe-rs/pull/846
