### ISSUE TITLE
Add the esp-rs/espressif team as owner for some crates

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-rs-backlog#10]
Presently the majority, if not all, of the repositories contained within this organization have been published to [crates.io](https://crates.io) by an individual.

We should consider eventually adding the `esp-rs/espressif` team (or possibly making another team just for this purpose) as owners for at least some of these crates, just to reduce dependence on certain individuals when cutting new releases and to increase our [bus factor](https://en.wikipedia.org/wiki/Bus_factor).

**Comment by MabezDev** [comment]
Somehow I missed this! Will work on adding the esp-rs/espressif team to the crates I've published.

**Comment by jessebraham** [comment]
Thanks! I have added the team as owner on the `esp32c3` and `esp32s2` crates as well. You are the owner of `esp32` so when you get a chance could you please add that one as well?

**Comment by jessebraham** [comment]
I believe these are the remaining packages which have not yet had the team added as an owner?

- [ ] esp-idf-hal
- [ ] esp-idf-svc
- [ ] esp-idf-sys
- [ ] espmonitor
- [ ] embedded-svc
- [ ] esp32
- [ ] esp32-hal
- [ ] xtensa-lx
- [ ] riscv-atomic-emulation-trap

**Comment by MabezDev** [comment]
I've updated all that I can, I don't have access on crates.io for the idf crates or espmonitor. It's less important for the idf crates as @ivmarkov has setup gh actions to publish to crates.io, but eventually it would be nice add the espressif team to them too.

**Comment by MabezDev** [comment]
> So what I would do is to add you as an owner of the esp idf crates, and then perhaps you can add the Espressif team then.

Thanks! I've added the espressif team to the idf crates.

> Related: how do we feel about moving embuild from my own GitHub space to esp-rs? It is maybe kind of important, given that the build of the esp idf crates depends on it?

Sure! It's kind of esp specific so I suppose it makes sense :)

**Comment by ivmarkov** [comment]
OK, so `embuild` is now transferred to `esp-rs`.
I've also invited you as an owner in `crates.io` so that you can invite the rest of the Espressif crew there.

After the transfer, I don't have permissions to the `embuild` GitHub repo though. Can you assign me committer/maintainer permissions there?

**Comment by MabezDev** [comment]
> After the transfer, I don't have permissions to the embuild GitHub repo though. Can you assign me committer/maintainer permissions there?

Done! For you and @N3xed.

**Comment by kelnos** [comment]
@MabezDev sure, no problem, will take care of that when I'm at a computer.  Just a note, though, that this isn't necessary to make releases; you just need permissions on the GH repo to push commits and make releases (see https://github.com/esp-rs/espmonitor/blob/master/RELEASING.md).  (Granted, this will make it always appear on crates.io that _I_ made the release, which might not be desirable.)

**Comment by MabezDev** [comment]
> Just a note, though, that this isn't necessary to make releases; you just need permissions on the GH repo to push commits and make releases

Ah okay brilliant, that works :).

Let's close this, thanks folks!

**Comment by kelnos** [comment]
@MabezDev I added you as owner for `espmonitor` and `cargo-espmonitor`.  Regardless of the ability to publish via GH Actions, I figure it's good to increase the bus factor on ownership on crates.io anyway.  Feel free to add the espressif team if you like (sounds like I can't add it myself since I'm not on that team).
